name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: egor-tensin/setup-gcc@v1
      with:
        version: latest
        platform: x64
    - name: RM lld
      run: rm -rf .cargo
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
